# # import turtle
# # p=turtle.Turtle()
# # p.up()
# # p.goto(0,-50)
# # p.down()
# # p.begin_fill()
# # p.color("black")
# # p.fillcolor("Green")
# # p.circle(50)
# # p.end_fill()
# # # p.circle(50)
# # p.up()
# # p.goto(200,200)
# # p.down()
# # p.color("black")
# # p.begin_fill()
# # p.fillcolor("Orange")
# # p.circle(50)
# # p.end_fill()
# # # p.circle(50)
# # p.up()
# # p.goto(200,-200)
# # p.down()
# # p.color("black")
# # p.begin_fill()
# # p.fillcolor("red")
# # p.circle(50)
# # p.end_fill()
# # # p.circle(50)
# # p.up()
# # p.goto(-200,200)
# # p.down()
# # p.color("black")
# # p.begin_fill()
# # p.fillcolor("yellow")
# # p.circle(50)
# # p.end_fill()
# # # p.circle(50)
# # p.up()
# # p.goto(-200,-200)
# # p.down()
# # p.color("black")
# # p.begin_fill()
# # p.fillcolor("pink")
# # p.circle(50)
# # p.end_fill()
# # # p.circle(50)
# # turtle.exitonclick()

# # import turtle
# # def circle(x,y,color,rad):
# #     p=turtle.Turtle()
# #     p.up()
# #     p.goto(x,y)
# #     p.down()
# #     p.begin_fill()
# #     p.fillcolor(color)
# #     p.circle(rad)
# #     p.ht()
# #     p.end_fill()
# # circle(0,80,"purple",20)
# # circle(-280,-280,"brown",20)
# # circle(0,-50,"Green",50)
# # circle(200,200,"orange",50)
# # circle(200,-200,"yellow",50)
# # circle(-200,200,"blue",50)
# # circle(-200,-200,"red",50)
# # turtle.exitonclick()
# # import turtle
# # t=turtle.Turtle()
# # list=['purple','blue','red','yellow']
# # t.up()
# # t.goto(200,0)
# # for i in range(4):
# #     t.down()
# #     t.color(list[i])
# #     t.pensize(20)
# #     t.circle(100)
# #     t.up() 
# #     t.bk(100)
    
    
# # turtle.exitonclick()
# import turtle
# t=turtle.Turtle()
# # list=['blue','red','orange','purple','green']
# # for i in range(200):
# #     t.color(list[i%5])
# #     t.pensize(i/10+1)
# #     # t.forward(i)
# #     # t.left(90)
# #     # t.circle(i)
# #     t.speed(0)
# t.up()
# t.pensize(4)
# t.goto(0,-300)
# t.down()
# t.goto(0,300)
# def rectangle(color):
#     t.begin_fill()
#     t.fillcolor(color)
#     for i in range(2):
#         t.fd(400)
#         t.right(90)
#         t.fd(100)
#         t.right(90)
#     t.end_fill()
# rectangle("orange")
# t.goto(0,200)
# t.forward(200)
# t.color("#000088")
# t.circle(-50)
# t.setheading(270)
# t.forward(50)
# t.setheading(0)
# for i in range(24):
#     t.forward(45)
#     t.bk(45)
#     t.left(15)
# t.setheading(90)
# t.forward(50)
# t.setheading(0)
# t.color("black")
# t.forward(200)
# t.right(90)
# t.forward(100)
# t.right(90)
# t.fd(400)
# t.right(90)
# t.forward(100)
# t.rt(90)
# t.goto(0,100)
# rectangle("green")



# turtle.exitonclick()




import turtle
w=turtle.Screen()
w.bgcolor("black")
t=turtle.Turtle()
t.color("orange")
t.left(140)
t.fd(180)
t.begin_fill()
t.fillcolor("red")
t.circle(-90,200)
t.setheading(60)
t.circle(-90,200)
t.forward(180)
t.end_fill()
t.ht()
turtle.exitonclick()